name: Publish

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment:
      name: release

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: 3.9

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.9
          version: "0.5.24"

      - name: "Install dependencies"
        run: uv sync --all-extras --dev

      - name: "Build package & docs"
        run: "scripts/build"

      - name: "Publish to PyPI & deploy docs"
        run: "scripts/publish"
